
(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>django-admin startproject primero .

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>vim primero/settings.py
"vim" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>type primero/setting.py
La sintaxis del comando no es correcta.

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
June 08, 2020 - 15:53:39
Django version 3.0.7, using settings 'primero.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[08/Jun/2020 15:53:51] "GET / HTTP/1.1" 200 16389
[08/Jun/2020 15:53:52] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[08/Jun/2020 15:53:52] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[08/Jun/2020 15:53:52] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[08/Jun/2020 15:53:52] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
Not Found: /favicon.ico
[08/Jun/2020 15:53:52] "GET /favicon.ico HTTP/1.1" 404 1973

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying sessions.0001_initial... OK

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 08, 2020 - 16:07:48
Django version 3.0.7, using settings 'primero.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[08/Jun/2020 16:08:10] "GET / HTTP/1.1" 200 16389
[08/Jun/2020 16:08:10] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[08/Jun/2020 16:08:10] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[08/Jun/2020 16:08:10] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[08/Jun/2020 16:08:10] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[08/Jun/2020 16:08:15] "GET /admin HTTP/1.1" 301 0
[08/Jun/2020 16:08:15] "GET /admin/ HTTP/1.1" 302 0
[08/Jun/2020 16:08:23] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1966
[08/Jun/2020 16:08:23] "GET /static/admin/css/login.css HTTP/1.1" 200 1233
[08/Jun/2020 16:08:23] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18052
[08/Jun/2020 16:08:23] "GET /static/admin/css/base.css HTTP/1.1" 200 16378

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>python manage.py create superuser
Unknown command: 'create'. Did you mean migrate?
Type 'manage.py help' for usage.

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>python manage.py createsuperuser
Nombre de usuario (leave blank to use 'lucien'):
Dirección de correo electrónico: jgutierrezpum@unsa.edu.pe
Password:
Password (again):
Esta contraseña es demasiado corta. Debe contener al menos 8 caracteres.
Esta contraseña es demasiado común.
Bypass password validation and create user anyway? [y/N]: yes
Password:
Password (again):
Superuser created successfully.

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>python manage.py create superuser
Unknown command: 'create'. Did you mean migrate?
Type 'manage.py help' for usage.

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 08, 2020 - 16:12:51
Django version 3.0.7, using settings 'primero.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[08/Jun/2020 16:13:11] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
Forbidden (CSRF token missing or incorrect.): /admin/login/
[08/Jun/2020 16:13:32] "POST /admin/login/?next=/admin/ HTTP/1.1" 403 2524
[08/Jun/2020 16:14:04] "GET / HTTP/1.1" 200 16389
[08/Jun/2020 16:14:04] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[08/Jun/2020 16:14:04] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[08/Jun/2020 16:14:04] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[08/Jun/2020 16:14:04] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[08/Jun/2020 16:14:11] "GET /admin/ HTTP/1.1" 200 3112
[08/Jun/2020 16:14:11] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[08/Jun/2020 16:14:11] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[08/Jun/2020 16:14:11] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
[08/Jun/2020 16:14:11] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[08/Jun/2020 16:14:11] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[08/Jun/2020 16:14:22] "GET /admin/ HTTP/1.1" 200 3112
[08/Jun/2020 16:15:01] "GET /admin/auth/group/ HTTP/1.1" 200 3555
[08/Jun/2020 16:15:45] "GET /admin/auth/group/add/ HTTP/1.1" 200 6660
[08/Jun/2020 16:15:45] "GET /admin/jsi18n/ HTTP/1.1" 200 7069
[08/Jun/2020 16:15:45] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
[08/Jun/2020 16:15:45] "GET /static/admin/js/core.js HTTP/1.1" 200 5723
[08/Jun/2020 16:15:45] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6918
[08/Jun/2020 16:15:46] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
[08/Jun/2020 16:17:44] "GET /static/admin/css/forms.css HTTP/1.1" 200 8518
[08/Jun/2020 16:17:44] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1530
[08/Jun/2020 16:17:44] "GET / HTTP/1.1" 200 16389
[08/Jun/2020 16:17:44] "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 12318
[08/Jun/2020 16:17:44] "GET /static/admin/js/actions.js HTTP/1.1" 200 6766
[08/Jun/2020 16:17:44] "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 5753
[08/Jun/2020 16:17:44] "GET /static/admin/js/urlify.js HTTP/1.1" 200 8941
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55922)
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55923)
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55926)
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55925)
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55924)
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\ING.SISTEMAS\python\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\ING.SISTEMAS\python\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\ING.SISTEMAS\python\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\ING.SISTEMAS\python\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\ING.SISTEMAS\python\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\ING.SISTEMAS\python\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\ING.SISTEMAS\python\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "D:\ING.SISTEMAS\python\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
Traceback (most recent call last):
  File "D:\ING.SISTEMAS\python\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\ING.SISTEMAS\python\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\ING.SISTEMAS\python\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "D:\ING.SISTEMAS\python\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "D:\ING.SISTEMAS\python\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "D:\ING.SISTEMAS\python\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "D:\ING.SISTEMAS\python\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] Se ha anulado una conexión establecida por el software en su equipo host
  File "D:\ING.SISTEMAS\python\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
ConnectionAbortedError: [WinError 10053] Se ha anulado una conexión establecida por el software en su equipo host
----------------------------------------
  File "D:\ING.SISTEMAS\python\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
----------------------------------------
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
ConnectionAbortedError: [WinError 10053] Se ha anulado una conexión establecida por el software en su equipo host
  File "D:\ING.SISTEMAS\python\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
----------------------------------------
ConnectionAbortedError: [WinError 10053] Se ha anulado una conexión establecida por el software en su equipo host
----------------------------------------
  File "D:\ING.SISTEMAS\python\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "D:\ING.SISTEMAS\python\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] Se ha anulado una conexión establecida por el software en su equipo host
----------------------------------------
[08/Jun/2020 16:18:32] "GET / HTTP/1.1" 200 16389
[08/Jun/2020 16:18:32] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[08/Jun/2020 16:18:33] "GET / HTTP/1.1" 200 16389
[08/Jun/2020 16:18:34] "GET / HTTP/1.1" 200 16389
[08/Jun/2020 16:18:34] "GET / HTTP/1.1" 200 16389
[08/Jun/2020 16:18:42] "GET /admin/ HTTP/1.1" 200 3112
[08/Jun/2020 16:18:42] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[08/Jun/2020 16:18:42] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[08/Jun/2020 16:18:42] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[08/Jun/2020 16:18:42] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[08/Jun/2020 16:18:42] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[08/Jun/2020 16:18:42] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[08/Jun/2020 16:18:42] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[08/Jun/2020 16:18:42] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[08/Jun/2020 16:18:44] "GET /admin/auth/group/ HTTP/1.1" 200 3555
[08/Jun/2020 16:18:44] "GET /admin/jsi18n/ HTTP/1.1" 200 7069
[08/Jun/2020 16:18:44] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6190
[08/Jun/2020 16:18:44] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
[08/Jun/2020 16:18:45] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[08/Jun/2020 16:18:45] "GET /static/admin/img/search.svg HTTP/1.1" 200 458
[08/Jun/2020 16:18:47] "GET /admin/ HTTP/1.1" 200 3112
[08/Jun/2020 16:18:48] "GET /admin/auth/user/ HTTP/1.1" 200 6753
[08/Jun/2020 16:18:48] "GET /admin/jsi18n/ HTTP/1.1" 200 7069
[08/Jun/2020 16:18:48] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[08/Jun/2020 16:18:48] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[08/Jun/2020 16:18:49] "GET /admin/ HTTP/1.1" 200 3112
[08/Jun/2020 16:18:50] "GET /admin/auth/group/add/ HTTP/1.1" 200 6660
[08/Jun/2020 16:18:50] "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
[08/Jun/2020 16:18:50] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
[08/Jun/2020 16:18:51] "GET /admin/jsi18n/ HTTP/1.1" 200 7069
[08/Jun/2020 16:18:51] "GET /static/admin/css/widgets.css HTTP/1.1" 200 10322
[08/Jun/2020 16:18:51] "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
[08/Jun/2020 16:18:51] "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
[08/Jun/2020 16:18:51] "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
[08/Jun/2020 16:18:55] "GET /admin/ HTTP/1.1" 200 3112

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>python manage.py startapp personas

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>ls
"ls" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>tree personas
Listado de rutas de carpetas para el volumen Data
El número de serie del volumen es 78D8-4DF8
D:\ING.SISTEMAS\PYTHON\CGI-BIN\PERSONAS
└───migrations

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>python manage.py makemigrations
No changes detected

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "D:\ING.SISTEMAS\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'persona'

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "D:\ING.SISTEMAS\python\cgi-bin\project-prueba\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "D:\ING.SISTEMAS\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\ING.SISTEMAS\python\cgi-bin\personas\models.py", line 5
    nombre     = models.TextField[]
                                  ^
SyntaxError: invalid syntax

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>
(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>python manage.py makemigrations
Migrations for 'personas':
  personas\migrations\0001_initial.py
    - Create model Persona

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, personas, sessions
Running migrations:
  Applying personas.0001_initial... OK

(project-prueba) D:\ING.SISTEMAS\python\cgi-bin>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 08, 2020 - 16:38:06
Django version 3.0.7, using settings 'primero.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[08/Jun/2020 16:38:08] "GET /admin/ HTTP/1.1" 200 3814
[08/Jun/2020 16:38:08] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[08/Jun/2020 16:38:08] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[08/Jun/2020 16:38:08] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[08/Jun/2020 16:38:08] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[08/Jun/2020 16:38:08] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[08/Jun/2020 16:38:08] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[08/Jun/2020 16:38:08] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[08/Jun/2020 16:38:08] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[08/Jun/2020 16:38:08] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[08/Jun/2020 16:38:37] "GET /admin/personas/persona/ HTTP/1.1" 200 3239
[08/Jun/2020 16:38:37] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[08/Jun/2020 16:38:37] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[08/Jun/2020 16:38:37] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[08/Jun/2020 16:38:37] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[08/Jun/2020 16:38:37] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[08/Jun/2020 16:38:37] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[08/Jun/2020 16:38:37] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[08/Jun/2020 16:38:37] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[08/Jun/2020 16:38:37] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[08/Jun/2020 16:38:37] "GET /admin/jsi18n/ HTTP/1.1" 200 7069
[08/Jun/2020 16:38:37] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
[08/Jun/2020 16:38:42] "GET /admin/personas/persona/add/ HTTP/1.1" 200 5069
[08/Jun/2020 16:38:42] "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
[08/Jun/2020 16:38:42] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[08/Jun/2020 16:38:42] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
[08/Jun/2020 16:38:42] "GET /admin/jsi18n/ HTTP/1.1" 200 7069
[08/Jun/2020 16:38:42] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[08/Jun/2020 16:39:10] "POST /admin/personas/persona/add/ HTTP/1.1" 302 0
[08/Jun/2020 16:39:10] "GET /admin/personas/persona/ HTTP/1.1" 200 4640
[08/Jun/2020 16:39:10] "GET /admin/jsi18n/ HTTP/1.1" 200 7069
[08/Jun/2020 16:39:10] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
[08/Jun/2020 16:39:12] "GET /admin/personas/persona/1/change/ HTTP/1.1" 200 5310
[08/Jun/2020 16:39:12] "GET /admin/jsi18n/ HTTP/1.1" 200 7069
[08/Jun/2020 16:39:18] "GET /admin/personas/persona/ HTTP/1.1" 200 4440
[08/Jun/2020 16:39:19] "GET /admin/jsi18n/ HTTP/1.1" 200 7069